// GENERATED by scripts/mcp/generate-distribution.mjs — do not edit by hand.
/**
 * What an unauthenticated caller is told.
 *
 * MCP clients relay a tool error straight to the model and on to the user, so
 * this text IS the product's authentication UX. It must always carry: the
 * browser path, the manual API-key path with a real URL, and where the key goes.
 */

export const AUTH_URLS = {
  /** Consent screen used by the `login` tool's browser handshake. */
  authorize: "https://reach.misar.io/authorize",
  /** Dashboard page where a key is created by hand. */
  apiKeys: "https://reach.misar.io/settings/api-keys",
  docs: "https://docs.misar.io/reach/mcp",
} as const;

/**
 * Whether this product ships the browser sign-in flow.
 *
 * When false the guidance offers ONLY the manual key path: advertising a
 * `login` tool that is not registered, or an /authorize page that 404s,
 * strands the user worse than saying nothing at all. Flip this in the same
 * change that ships the consent page and the auth tools.
 */
export const HAS_BROWSER_LOGIN = true;

export const KEY_PREFIX = "mrk_";
export const ENV_KEY = "MISARREACH_API_KEY";
export const CONFIG_PATH = "~/.misarreach/config.json";

/**
 * The full guidance block.
 *
 * `reason` distinguishes "you never authenticated" from "your key was
 * rejected" — the remedies differ, and telling someone with an expired key to
 * create their first one wastes their time.
 */
export function authGuidance(reason: "missing" | "rejected" = "missing"): string {
  const headline =
    reason === "rejected"
      ? "Your MisarReach API key was rejected (it may have been revoked or rotated)."
      : "Not authenticated with MisarReach.";

  return [
    headline,
    "",
    ...(HAS_BROWSER_LOGIN
      ? [
          "Choose either option — both take under a minute.",
          "",
          "OPTION 1 — Sign in with your browser (recommended, no copy-paste)",
          "  Run the `login` tool. It opens:",
          `    ${AUTH_URLS.authorize}`,
          "  Review the requested permissions, click Authorize, and the key is written",
          `  to ${CONFIG_PATH} automatically. Nothing else to configure.`,
          "",
          "OPTION 2 — Create an API key by hand",
        ]
      : ["Create an API key — it takes under a minute."]),
    `  1. Open ${AUTH_URLS.apiKeys}`,
    "     (Settings → API keys)",
    `  2. Create a key — it starts with ${KEY_PREFIX}`,
    "  3. Give it to this server in ONE of these ways:",
    "",
    "     a) Environment variable (works everywhere, incl. cloud/CI):",
    `          export ${ENV_KEY}="${KEY_PREFIX}your_key_here"`,
    "",
    "     b) MCP client config — add it to the server's env block, e.g.",
    "        Claude Desktop / Claude Code / Cursor / Windsurf / Cline:",
    `          "env": { "${ENV_KEY}": "${KEY_PREFIX}your_key_here" }`,
    "        VS Code prompts for it instead of storing it in the file.",
    "",
    `     c) Config file — write { "api_key": "${KEY_PREFIX}..." } to ${CONFIG_PATH}`,
    "",
    "  Then restart your MCP client so it picks up the new value.",
    "",
    `Full setup guide: ${AUTH_URLS.docs}`,
  ].join("\n");
}
