// @generated by misar-io/scripts/generate-vendored-upsell.mjs — DO NOT EDIT.
//
// Source:  misar-io/packages/upsell/src/{contract,detect,render}.ts
// upsell-source-sha256: 375a64cfeee1f45743347f956d47e5bf2d68f05935a545b959a803eafa17283f
//
// This is a VENDORED copy, not laziness: these MCP servers publish to public
// npm while @misar/upsell lives on the private registry, so a dependency here
// would break `npm i` for every end user. Edit the package and regenerate —
// an edit made in this file is lost on the next run, and CI fails on drift.

// ── from @misar/upsell/contract.ts ───────────────────────────────────

/**
 * The upsell wire contract — shared by every Misar product.
 *
 * A single shape describes "you are blocked, here is how to unblock" across
 * MisarBlog, MisarMail, MisarReach and MisarPost, so one renderer in an MCP
 * client works for all of them and one dashboard can measure all of them.
 *
 * DESIGN RULE: all user-visible copy (plan names, prices, benefit bullets,
 * URLs) travels INSIDE this payload. MCP servers are published to npm and
 * external marketplaces, so text baked into a client can only change by
 * republishing and re-submitting everywhere. Keeping copy server-side means
 * marketing can retune the entire upsell and every already-installed client
 * renders the new content on its next blocked call.
 */

/** Products that can emit an upsell. */
export type UpsellProduct = "blog" | "mail" | "reach" | "post" | "io";

export type UpgradeReason =
  /** A metered allowance is spent (retryable when the period rolls over). */
  | "quota_exhausted"
  /** The feature isn't part of the current plan at all. */
  | "feature_locked"
  /** Pay-as-you-go is on, but the spend cap is reached. */
  | "overage_capped"
  /** Wallet balance is too low for this action (1 credit = $1 USD). */
  | "credits_exhausted";

export interface UpgradePlanOption {
  slug: string;
  name: string;
  /** Display price, e.g. "$4.99/month" or "Custom pricing". */
  price: string;
  /** Secondary price line, e.g. "or $47.90/year — 2 months free". */
  price_note: string | null;
  recommended: boolean;
  current: boolean;
  /** What this plan does about the SPECIFIC limit that was hit. */
  unlocks: string | null;
  /** Broader reasons to move up. */
  benefits: string[];
  url: string;
}

export interface UsageSnapshot {
  used: number | null;
  limit: number | null;
  remaining: number | null;
  period: "day" | "month" | "total" | null;
  /** ISO timestamp when a metered period rolls over; null if not periodic. */
  resets_at: string | null;
}

/** A no-card trial the user can start to unblock themselves immediately. */
export interface TrialOffer {
  available: boolean;
  plan_slug: string;
  plan_name: string;
  days: number;
  /** Endpoint an MCP client can POST to in order to start the trial. */
  start_url: string;
  requires_card: boolean;
  label: string;
}

/** Another Misar product that solves the need behind this limit. */
export interface CrossSellOffer {
  product: UpsellProduct;
  product_name: string;
  headline: string;
  url: string;
}

export interface TopupOffer {
  balance_credits: number;
  required_credits: number;
  options: { amount_dollars: number; label: string; url: string }[];
}

export interface UpgradeOffer {
  product: UpsellProduct;
  product_name: string;
  reason: UpgradeReason;
  /** Stable machine key, e.g. "mcp_write_actions". */
  feature: string;
  /** Human label, e.g. "Automation write actions". */
  feature_label: string;
  /** One-line explanation of exactly what was hit. */
  headline: string;
  usage: UsageSnapshot | null;
  current_plan: { slug: string; name: string };
  recommended_plan: string | null;
  plans: UpgradePlanOption[];
  /** Present only for `credits_exhausted`. */
  topup: TopupOffer | null;
  /** Pay-as-you-go alternative, when the feature supports it. */
  overage: { available: boolean; enabled: boolean; hint: string; url: string } | null;
  /** Immediate self-serve unblock, shown above the paid plans. */
  trial: TrialOffer | null;
  /** Suggestions for other Misar products, at most one or two. */
  cross_sell: CrossSellOffer[];
  urls: { pricing: string; billing: string; docs: string; compare: string };
  cta: string;
  /** Correlates the block with a later checkout — see the funnel dashboard. */
  event_id?: string | null;
}

/** The full JSON body a blocked API call returns. */
export interface PlanLimitBody {
  error: string;
  code: "plan_limit_exceeded";
  upgrade: UpgradeOffer;
  /** Products may add legacy top-level fields for back-compat. */
  [key: string]: unknown;
}

/** Response headers carrying live usage on SUCCESSFUL metered calls. */
export const USAGE_HEADERS = {
  feature: "x-misar-usage-feature",
  used: "x-misar-usage-used",
  limit: "x-misar-usage-limit",
  remaining: "x-misar-usage-remaining",
  resets: "x-misar-usage-resets",
  plan: "x-misar-plan",
  upgradeUrl: "x-misar-upgrade-url",
} as const;

/**
 * Headers describing a PREPAID balance on a successful metered call.
 *
 * Deliberately separate from USAGE_HEADERS. Those describe a quota with a
 * denominator — `used` of `limit` — and `usageFooter` fires at 80% of it.
 * A prepaid wallet has no denominator: coercing balance into used/limit makes
 * `ratio` arithmetic meaningless and fires the warning at the wrong moment.
 * So prepaid gets its own signal, thresholded on a number the USER chose
 * (their auto-reload threshold), not on a fraction we invented.
 */
export const BALANCE_HEADERS = {
  credits: "x-misar-balance-credits",
  threshold: "x-misar-balance-threshold",
} as const;

// ── from @misar/upsell/detect.ts ─────────────────────────────────────

/**
 * Client-side helpers: recognising a plan-limit rejection, and turning the
 * usage headers on a SUCCESSFUL response into a pre-emptive warning.
 */


/** Extract the offer from an arbitrary API error body, if present. */
export function extractUpgradeOffer(body: unknown): UpgradeOffer | null {
  if (typeof body !== "object" || body === null) return null;
  const b = body as Record<string, unknown>;
  if (b.code !== "plan_limit_exceeded") return null;
  const offer = b.upgrade;
  if (typeof offer !== "object" || offer === null) return null;
  const o = offer as Partial<UpgradeOffer>;
  // Minimal shape check — never render a half-populated card.
  if (typeof o.headline !== "string" || !Array.isArray(o.plans)) return null;
  return offer as UpgradeOffer;
}

export interface UsageWarning {
  feature: string;
  used: number;
  limit: number;
  remaining: number;
  ratio: number;
  upgradeUrl: string | null;
  resetsAt: string | null;
}

/**
 * Read the usage headers off a successful response.
 * Returns null when the route isn't metered or the headers are absent.
 */
export function parseUsageHeaders(headers: {
  get(name: string): string | null;
}): UsageWarning | null {
  const feature = headers.get(USAGE_HEADERS.feature);
  const usedRaw = headers.get(USAGE_HEADERS.used);
  const limitRaw = headers.get(USAGE_HEADERS.limit);
  if (!feature || usedRaw === null || limitRaw === null) return null;

  const used = Number(usedRaw);
  const limit = Number(limitRaw);
  // limit <= 0 means unlimited (or nonsense) — nothing to warn about.
  if (!Number.isFinite(used) || !Number.isFinite(limit) || limit <= 0) return null;

  const remainingRaw = headers.get(USAGE_HEADERS.remaining);
  const remaining =
    remainingRaw !== null && Number.isFinite(Number(remainingRaw))
      ? Number(remainingRaw)
      : Math.max(0, limit - used);

  return {
    feature,
    used,
    limit,
    remaining,
    ratio: used / limit,
    upgradeUrl: headers.get(USAGE_HEADERS.upgradeUrl),
    resetsAt: headers.get(USAGE_HEADERS.resets),
  };
}

/** Warn from this fraction of the allowance onward. */
export const WARN_THRESHOLD = 0.8;

/**
 * A one-line footer appended to SUCCESSFUL tool output once usage crosses the
 * threshold.
 *
 * Catching someone at 80% — while the task is still working — converts far
 * better than an error at 100%, and it reads as helpful rather than pushy.
 * Returns null below the threshold so the vast majority of calls stay clean.
 */
export function usageFooter(
  warning: UsageWarning | null,
  featureLabel?: string,
): string | null {
  if (!warning) return null;
  if (warning.ratio < WARN_THRESHOLD) return null;
  if (warning.remaining <= 0) return null; // already blocked — the card covers it

  const label = (featureLabel ?? warning.feature.replace(/_/g, " ")).toLowerCase();
  const tail = warning.upgradeUrl ? ` — more at ${warning.upgradeUrl}` : "";

  return (
    `\n\n⚡ ${warning.remaining.toLocaleString("en-US")} of ` +
    `${warning.limit.toLocaleString("en-US")} ${label} left. ` +
    `Run \`upgrade\` to see your options${tail}`
  );
}


export interface BalanceWarning {
  credits: number;
  threshold: number;
  upgradeUrl: string | null;
}

/**
 * Read the prepaid balance headers off a successful response.
 * Returns null when the route is not prepaid-metered, or the balance is healthy.
 */
export function parseBalanceWarning(headers: {
  get(name: string): string | null;
}): BalanceWarning | null {
  const creditsRaw = headers.get(BALANCE_HEADERS.credits);
  if (creditsRaw === null) return null;

  const credits = Number(creditsRaw);
  if (!Number.isFinite(credits)) return null;

  const thresholdRaw = headers.get(BALANCE_HEADERS.threshold);
  const threshold =
    thresholdRaw !== null && Number.isFinite(Number(thresholdRaw)) ? Number(thresholdRaw) : 10;

  // Above the threshold there is nothing worth interrupting anyone about.
  if (credits > threshold) return null;

  return { credits, threshold, upgradeUrl: headers.get(USAGE_HEADERS.upgradeUrl) };
}

/**
 * A one-line footer for a running-low wallet, appended to SUCCESSFUL output.
 *
 * Catching someone while their task still works converts far better than an
 * error after it stopped, and it reads as helpful rather than pushy.
 */
export function balanceFooter(warning: BalanceWarning | null): string | null {
  if (!warning) return null;
  const tail = warning.upgradeUrl ? ` — top up at ${warning.upgradeUrl}` : "";
  const amount = Number.isInteger(warning.credits)
    ? warning.credits.toLocaleString("en-US")
    : String(Math.round(warning.credits * 100) / 100);
  return `\n\n⚡ ${amount} credits left in your wallet${tail}`;
}

// ── from @misar/upsell/render.ts ─────────────────────────────────────

/**
 * CLI renderers for the upsell contract.
 *
 * Pure formatting — no product knowledge, no network, no dependencies. Every
 * word shown comes from the payload, so this file never needs to change when
 * pricing or marketing copy does.
 *
 * Output is plain text with box drawing: readable raw in a terminal, and
 * rendered cleanly by MCP clients that treat tool output as markdown.
 */


const WIDTH = 62;

const rule = (char = "─") => char.repeat(WIDTH);

/** A 20-cell usage bar: ████████████░░░░░░░░  80% */
export function usageBar(used: number, limit: number, cells = 20): string {
  const ratio = limit <= 0 ? 1 : Math.min(1, used / limit);
  const filled = Math.round(ratio * cells);
  return `${"█".repeat(filled)}${"░".repeat(cells - filled)}  ${Math.round(ratio * 100)}%`;
}

export function humanDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const date = d.toLocaleDateString("en-US", {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  });
  const days = Math.max(0, Math.ceil((d.getTime() - Date.now()) / 86_400_000));
  return days === 0 ? `${date} (today)` : `${date} (in ${days} day${days === 1 ? "" : "s"})`;
}

const field = (label: string, value: string) => `  ${label.padEnd(10)}${value}`;

function periodWord(period: UsageSnapshot["period"]): string {
  if (period === "month") return " this month";
  if (period === "day") return " today";
  return "";
}

/** Render the full upgrade card shown when a call is blocked. */
export function renderUpgradeOffer(offer: UpgradeOffer): string {
  const out: string[] = [];

  const banner =
    offer.reason === "credits_exhausted"
      ? "Out of credits"
      : offer.reason === "feature_locked"
        ? "This feature needs a higher plan"
        : offer.reason === "overage_capped"
          ? "Limit reached and overage cap hit"
          : "You've hit your plan limit";

  // `⚠` renders double-width in most terminals, so the visible cost of the
  // prefix is 6 columns, not 5 — pad against that or the box closes crooked.
  const bannerLine = `  ⚠  ${banner}`.padEnd(WIDTH - 1);

  out.push("");
  out.push(`╭${rule()}╮`);
  out.push(`│${bannerLine}│`);
  out.push(`╰${rule()}╯`);
  out.push("");
  out.push(`  ${offer.headline}`);
  out.push("");

  out.push(field("Feature", offer.feature_label));
  if (offer.usage && offer.usage.limit !== null && offer.usage.used !== null) {
    out.push(
      field(
        "Usage",
        `${offer.usage.used.toLocaleString("en-US")} / ${offer.usage.limit.toLocaleString("en-US")}${periodWord(offer.usage.period)}`,
      ),
    );
    out.push(field("", usageBar(offer.usage.used, offer.usage.limit)));
  }
  if (offer.topup) {
    out.push(field("Balance", `${offer.topup.balance_credits} credits`));
    out.push(field("Required", `${offer.topup.required_credits} credits`));
  }
  if (offer.usage?.resets_at) out.push(field("Resets", humanDate(offer.usage.resets_at)));
  out.push(field("Plan", offer.current_plan.name));
  out.push("");

  // ── Trial first: the cheapest possible "yes" ──────────────────────────────
  // Shown above the paid plans deliberately. The user is mid-task with maximum
  // intent; a no-card trial converts that moment far better than a price tag.
  if (offer.trial?.available) {
    out.push(`  ${rule("┄")}`);
    out.push("");
    out.push(`  ✨ ${offer.trial.label}`);
    out.push(
      `     Start a ${offer.trial.days}-day ${offer.trial.plan_name} trial` +
        `${offer.trial.requires_card ? "" : " — no card required"} and keep going now.`,
    );
    out.push(`     Run: upgrade start_trial=true`);
    out.push("");
  }

  if (offer.plans.length > 0) {
    out.push(`  ${rule("┄")}`);
    out.push("");
    out.push("  Upgrade to keep going — and unlock a lot more:");
    out.push("");

    for (const plan of offer.plans) {
      const badge = plan.recommended ? "   ★ RECOMMENDED" : "";
      out.push(`  ▸ ${plan.name} — ${plan.price}${badge}`);
      if (plan.price_note) out.push(`    ${plan.price_note}`);
      if (plan.unlocks) out.push(`    ✔ Fixes this: ${plan.unlocks}`);
      // Cap the bullets so the card stays scannable; the compare URL has the rest.
      for (const benefit of plan.benefits.slice(0, 6)) out.push(`      · ${benefit}`);
      if (plan.benefits.length > 6) {
        out.push(`      · …and ${plan.benefits.length - 6} more`);
      }
      out.push(`    → ${plan.url}`);
      out.push("");
    }
  }

  // Pay-as-you-go is often the cheaper honest answer — surfacing it builds
  // trust and still monetises the call.
  if (offer.overage?.available) {
    out.push(`  ${rule("┄")}`);
    out.push("");
    out.push(`  ${offer.overage.hint}`);
    out.push(`  → ${offer.overage.url}`);
    out.push("");
  }

  if (offer.topup) {
    out.push(`  ${rule("┄")}`);
    out.push("");
    out.push("  Top up your wallet to keep going:");
    out.push("");
    for (const option of offer.topup.options) {
      out.push(`  ▸ ${option.label}`);
      out.push(`    → ${option.url}`);
    }
    out.push("");
  }

  if (offer.cross_sell.length > 0) {
    out.push(`  ${rule("┄")}`);
    out.push("");
    out.push("  You might also need:");
    for (const item of offer.cross_sell) {
      out.push(`  ▸ ${item.product_name} — ${item.headline}`);
      out.push(`    → ${item.url}`);
    }
    out.push("");
  }

  out.push(`  ${rule("┄")}`);
  out.push("");
  out.push(`  ${offer.cta}`);
  out.push(`  Compare plans  → ${offer.urls.compare}`);
  out.push(`  Manage billing → ${offer.urls.billing}`);
  out.push(`  Limits & docs  → ${offer.urls.docs}`);
  out.push("");
  out.push("  Tip: run the `upgrade` tool any time to see your plan and what's left,");
  out.push("  or `upgrade open=true` to jump straight to checkout.");
  out.push("");

  return out.join("\n");
}

export interface UsageRow {
  feature: string;
  feature_label: string;
  used: number;
  limit: number | null;
  remaining: number | null;
  period: "day" | "month" | "total";
  resets_at: string | null;
}

/** Render the at-a-glance quota table used by the `upgrade` tool. */
export function renderUsageTable(
  productName: string,
  planName: string,
  usage: UsageRow[],
): string {
  const out: string[] = ["", `  ${productName} — ${planName} plan`, `  ${"─".repeat(58)}`, ""];

  if (usage.length === 0) {
    out.push("  No metered features on this plan.", "");
    return out.join("\n");
  }

  const width = Math.max(...usage.map((u) => u.feature_label.length));
  for (const row of usage) {
    if (row.limit === null) {
      out.push(`  ${row.feature_label.padEnd(width)}   ${"─".repeat(16)}  Unlimited`);
      continue;
    }
    const scope = row.period === "month" ? "this month" : row.period === "day" ? "today" : "total";
    out.push(
      `  ${row.feature_label.padEnd(width)}   ${usageBar(row.used, row.limit, 16)}   ` +
        `${row.used.toLocaleString("en-US")} / ${row.limit.toLocaleString("en-US")} ${scope}`,
    );
  }
  out.push("");
  return out.join("\n");
}

/** Compact one-liner for logs / nested contexts. */
export function summarizeOffer(offer: UpgradeOffer): string {
  return `${offer.headline} ${offer.cta} ${offer.urls.pricing}`;
}
