// @generated by misar-io/scripts/generate-vendored-upsell.mjs — DO NOT EDIT.
//
// Source:  misar-io/scripts/upsell/usage.template.ts
// upsell-source-sha256: 375a64cfeee1f45743347f956d47e5bf2d68f05935a545b959a803eafa17283f
/**
 * Pre-emptive usage warnings.
 *
 * Every successful metered call carries `x-misar-usage-*` headers describing
 * what the caller has left. Catching someone at 80% — while their task is still
 * working — converts far better than an error at 100%, and reads as helpful
 * rather than pushy.
 *
 * The last warning seen is stashed here and drained by the tool layer, so tools
 * do not each have to thread usage through their return path. The PARSING is
 * shared with `upgrade.ts` (itself generated from @misar/upsell) — this module
 * only adds the statefulness and the wording.
 */

import { parseUsageHeaders, WARN_THRESHOLD, type UsageWarning } from "./upgrade.js";

export type { UsageWarning };

let pending: UsageWarning | null = null;

/**
 * Read the usage headers off a response; stash a warning if we're close.
 *
 * Never throws. This runs on the hot path of EVERY API call, so a response
 * without a standard `headers` object — a proxy, a test double, an older
 * runtime — must degrade to "no warning", never break the call itself.
 */
export function noteUsage(headers: Headers | null | undefined): void {
  // Reset FIRST. Every response clears the previous state, so a warning raised
  // by an earlier metered write can never leak onto a later unrelated call —
  // which would show the user a footer that has nothing to do with what they
  // just did.
  pending = null;

  if (!headers || typeof headers.get !== "function") return;

  const warning = parseUsageHeaders(headers);
  if (!warning) return;

  // Below the threshold, or already blocked (the upgrade card covers that case).
  if (warning.ratio < WARN_THRESHOLD || warning.remaining <= 0) return;

  pending = warning;
}

/** Take (and clear) the pending warning as a one-line footer, if any. */
export function takeUsageFooter(): string | null {
  const warning = pending;
  pending = null;
  if (!warning) return null;

  const label = warning.feature.replace(/_/g, " ");
  const tail = warning.upgradeUrl ? `\n   More at ${warning.upgradeUrl}` : "";

  return (
    `\n\n⚡ ${warning.remaining.toLocaleString("en-US")} of ` +
    `${warning.limit.toLocaleString("en-US")} ${label} left. ` +
    `Run \`upgrade\` to see your options.${tail}`
  );
}

/** Append the pending warning to a tool's text result, when there is one. */
export function withUsageFooter(text: string): string {
  const footer = takeUsageFooter();
  return footer ? `${text}${footer}` : text;
}
